第 5 课
========================================================
```{r Premise}
setwd("G:/ku/udacity_dand_advanced/P6_R_Basics/lesson4")
suppressMessages(library(ggplot2))
suppressMessages(library(dplyr))
pf <- read.csv('pseudo_facebook.tsv', sep = '\t')
```

### 多变量数据
注释：

***

### 年龄标记为彩色的自我感知关注量
注释：

***

### 第三个定性变量
注释：

```{r Third Qualitative Variable}
pf.fc_by_age_gender <- pf %>%
  filter(!is.na(gender)) %>%
  group_by(age, gender) %>%
  summarise(mean_friend_count = mean(friend_count),
            median_friend_count = median(friend_count),
            n = n()) %>%
  ungroup() %>%
  arrange(age)

```

***

### 绘制条件总结
注释：

```{r Plotting Conditional Summaries}
# Create a line graph showing the
# median friend count over the ages
# for each gender. Be sure to use
# the data frame you just created,
# pf.fc_by_age_gender.

# See the Instructor Notes for a hint.

# This assignment is not graded and
# will be marked as correct when you submit.

# ENTER YOUR CODE BELOW THIS LINE
# =================================================
ggplot(data = subset(pf, !is.na(gender)), aes(x = age, y = friend_count)) +
  geom_line(aes(color = gender), stat = 'summary', fun.y = median)
```

***

### 思考比率
注释：

***

### 又宽又长的格式
注释：

***

### 改变数据
注释：

```{r}
install.packages('reshape2')
library(reshape2)
```

***

### 比率图
注释：

```{r Ratio Plot}
# Plot the ratio of the female to male median
# friend counts using the data frame
# pf.fc_by_age_gender.wide.

# Think about what geom you should use.
# Add a horizontal line to the plot with
# a y intercept of 1, which will be the
# base line. Look up the documentation
# for geom_hline to do that. Use the parameter
# linetype in geom_hline to make the
# line dashed.

# The linetype parameter can take the values 0-6:
# 0 = blank, 1 = solid, 2 = dashed
# 3 = dotted, 4 = dotdash, 5 = longdash
# 6 = twodash

# This assignment is not graded and
# will be marked as correct when you submit.

# ENTER YOUR CODE BELOW THIS LINE
# =================================================
pf.fc_by_age_gender.wide <- dcast(pf.fc_by_age_gender,
                                  age ~ gender,
                                  value.var = 'median_friend_count')
ggplot(data = pf.fc_by_age_gender.wide, 
       aes(x = age, y = female / male))+
  geom_line() + 
  geom_hline(yintercept = 1, alpha = 0.3, linetype = 2, color = 'blue')
```

***

### 第三个定性变量
注释：

```{r Third Quantitative Variable}
pf$year_joined <- floor(2014 - (pf$tenure / 365))
```

***

### 减少一个变量
注释：

```{r Cut a Variable}
summary(pf$year_joined)
table(pf$year_joined)
pf$year_joined.bucket <- cut(pf$year_joined, c(2004, 2009, 2011, 2012, 2014))
```

***

### 同时绘制
注释：

```{r Plotting it All Together}
ggplot(data = subset(pf, !is.na(year_joined.bucket)),
       aes(x = age, y = friend_count)) +
  geom_line(aes(color = year_joined.bucket), stat = 'summary', fun.y = median)
```

***

### 绘制总平均值
注释：

```{r Plot the Grand Mean}
ggplot(data = subset(pf, !is.na(year_joined.bucket)),
       aes(x = age, y = friend_count)) +
  geom_line(aes(color = year_joined.bucket), stat = 'summary', fun.y = median) +
  geom_line(stat = 'summary', fun.y = median, linetype = 2)
```

***

### 交友率
注释：

```{r Friending Rate}
with(subset(pf, tenure >= 1), summary(friend_count / tenure))
```

***

### 开始交友
注释：

平均交友率是什么？

最大交友率是什么？

```{r Friendships Initiated}
ggplot(aes(x = tenure, y = friendships_initiated / tenure),
       data = subset(pf, tenure >= 1)) +
  geom_line(aes(color = year_joined.bucket),
            stat = 'summary',
            fun.y = mean)
```

***
### 偏差方差折衷
```{r}
ggplot(aes(x = 7 * round(tenure / 7), y = friendships_initiated / tenure),
       data = subset(pf, tenure > 0)) +
  geom_smooth(aes(color = year_joined.bucket))
```
### 再次访问方差权衡
注释：

```{r Bias-Variance Tradeoff Revisited}

ggplot(aes(x = tenure, y = friendships_initiated / tenure),
       data = subset(pf, tenure >= 1)) +
  geom_line(aes(color = year_joined.bucket),
            stat = 'summary',
            fun.y = mean)

ggplot(aes(x = 7 * round(tenure / 7), y = friendships_initiated / tenure),
       data = subset(pf, tenure > 0)) +
  geom_line(aes(color = year_joined.bucket),
            stat = "summary",
            fun.y = mean)

ggplot(aes(x = 30 * round(tenure / 30), y = friendships_initiated / tenure),
       data = subset(pf, tenure > 0)) +
  geom_line(aes(color = year_joined.bucket),
            stat = "summary",
            fun.y = mean)

ggplot(aes(x = 90 * round(tenure / 90), y = friendships_initiated / tenure),
       data = subset(pf, tenure > 0)) +
  geom_line(aes(color = year_joined.bucket),
            stat = "summary",
            fun.y = mean)



```

***

### Sean 对 NFL 粉丝情绪的研究
注释：

***

###  Yogurt 数据集简介
注释：

***

### 再次访问直方图
注释：

```{r Histograms Revisited}
yo <- read.csv('yogurt.csv')
str(yo)

yo$id <- factor(yo$id)
str(yo)

ggplot(data = yo, aes(x = price, fill = '#FFFFFF')) + 
  geom_histogram(binwidth = 10)
```

***

### 购买数量
注释：

```{r Number of Purchases}
yo <- transform(yo, all.purchases = strawberry +
                  blueberry + pina.colada + 
                  plain +mixed.berry)
```

***

### 一段时期的价格
注释：

```{r Prices over Time}
ggplot(data = yo, aes(x = time, y = price)) +
  geom_jitter(alpha = 0.25, shape = 21, fill = I('#F79420'))
```

***

### 抽样观察
注释：

***

### 观察家庭的样本

```{r Looking at Sample of Households}
set.seed(4444)  # 设定随机种子，可复现
sample.ids <- sample(levels(yo$id), 16)  # 设定16个变量

ggplot(data = subset(yo, id %in% sample.ids),
       aes(x = time, y = price)) +
  facet_wrap( ~ id) +
  geom_line() +
  geom_point(aes(size = all.purchases), pch = 1)
```

***

### 交叉分组数据的缺点
注释：

***

### 许多变量
注释：

***

### 散点图矩阵
注释：
```{r}
library(GGally)
theme_set(theme_minimal(20))

set.seed(1836)
pf_subset <- pf[, c(2:15)]
names(pf_subset)
ggpairs(pf_subset[sample.int(nrow(pf_subset), 1000), ])
```

***

### 更多变量
注释：

***

### 热点图
注释：

```{r}
nci <- read.table("nci.tsv")
colnames(nci) <- c(1:64)
```

```{r}
nci.long.samp <- melt(as.matrix(nci[1:200,]))
names(nci.long.samp) <- c("gene", "case", "value")
head(nci.long.samp)

ggplot(aes(y = gene, x = case, fill = value),
  data = nci.long.samp) +
  geom_tile() +
  scale_fill_gradientn(colours = colorRampPalette(c("blue", "red"))(100))
```

***

### 分析三个及三个以上变量
思考：

***

点击 **KnitHTML** 查看你的成果和这节课的 html 页面、
答案和注释！
